
DROP USER GAMEADMIN;

CREATE USER GAMEADMIN IDENTIFIED BY gameAdminpassword3;

GRANT SELECT, INSERT, UPDATE, DELETE ON USER_INFO TO GAMEADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON LEVEL_INFO TO GAMEADMIN;

GRANT CREATE SESSION TO GAMEADMIN;

GRANT CREATE TABLE TO GAMEADMIN;



DROP TABLE USER_INFO;

DROP TABLE LEVEL_INFO;

CREATE TABLE USER_INFO(
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    LEVELS_COMPLETED NUMBER,
    HAS_STARTED_GAME CHAR(1) CHECK (HAS_STARTED_GAME IN ('0', '1')),
    CONSTRAINT PK_EMAIL PRIMARY KEY (EMAIL)
);

CREATE TABLE LEVEL_INFO(
    EMAIL VARCHAR(50) NOT NULL,
    LEVEL_NUMBER NUMBER,
    SCORE NUMBER,
    TIME_TAKEN NUMBER,
    CONSTRAINT PK_EMAIL_AND_LEVEL PRIMARY KEY (EMAIL, LEVEL_NUMBER),
    CONSTRAINT FK_EMAIL FOREIGN KEY (EMAIL) REFERENCES USER_INFO ON DELETE CASCADE
);

select * from user_info;

